name: Daily News Collection

on:
  workflow_dispatch:      # ğŸ‘ˆ ìˆ˜ë™ ì‹¤í–‰ ê°€ëŠ¥!
  schedule:
    - cron: '0 23 * * *'   # ë§¤ì¼ ì˜¤ì „ 8ì‹œ(KST)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run irobotnews collector
      run: python collect_irobotnews.py

    - name: Run MIT news collector
      run: python collect_MIT_news.py

    - name: Run The Verge news collector
      run: python collect_theverge_news.py

    - name: Run VentureBeat news collector
      run: python collect_venturebeat_news.py
